// Generated from CDC/NCHS ICD-10-CM FY2026 code descriptions. Do not hand-edit entries.
import type { Icd10ConditionOption } from "./clinicalCatalog";

export const ICD10_FY2026_SOURCE = {
  name: "CDC/NCHS ICD-10-CM FY2026 code descriptions",
  effectiveFrom: "2025-10-01",
  effectiveThrough: "2026-09-30",
  url: "https://ftp.cdc.gov/pub/health_statistics/nchs/publications/ICD10CM/2026/icd10cm-Code%20Descriptions-2026.zip",
} as const;

export const OFFICIAL_ICD10_CONDITION_OPTIONS: Icd10ConditionOption[] = [
  { code: "I20.9", diagnosis: "Angina pectoris, unspecified", category: "Cardiovascular", search: [] },
  { code: "I10", diagnosis: "Essential (primary) hypertension", category: "Cardiovascular", search: [] },
  { code: "I50.9", diagnosis: "Heart failure, unspecified", category: "Cardiovascular", search: [] },
  { code: "I21.4", diagnosis: "Non-ST elevation (NSTEMI) myocardial infarction", category: "Cardiovascular", search: [] },
  { code: "I48.91", diagnosis: "Unspecified atrial fibrillation", category: "Cardiovascular", search: [] },
  { code: "E86.0", diagnosis: "Dehydration", category: "Endocrine / metabolic", search: [] },
  { code: "E16.2", diagnosis: "Hypoglycemia, unspecified", category: "Endocrine / metabolic", search: [] },
  { code: "E11.65", diagnosis: "Type 2 diabetes mellitus with hyperglycemia", category: "Endocrine / metabolic", search: [] },
  { code: "E11.9", diagnosis: "Type 2 diabetes mellitus without complications", category: "Endocrine / metabolic", search: [] },
  { code: "R19.7", diagnosis: "Diarrhea, unspecified", category: "Gastrointestinal", search: [] },
  { code: "R11.2", diagnosis: "Nausea with vomiting, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K52.9", diagnosis: "Noninfective gastroenteritis and colitis, unspecified", category: "Gastrointestinal", search: [] },
  { code: "R10.9", diagnosis: "Unspecified abdominal pain", category: "Gastrointestinal", search: [] },
  { code: "K35.80", diagnosis: "Unspecified acute appendicitis", category: "Gastrointestinal", search: [] },
  { code: "N30.00", diagnosis: "Acute cystitis without hematuria", category: "Genitourinary / renal", search: [] },
  { code: "N17.9", diagnosis: "Acute kidney failure, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N20.0", diagnosis: "Calculus of kidney", category: "Genitourinary / renal", search: [] },
  { code: "N39.0", diagnosis: "Urinary tract infection, site not specified", category: "Genitourinary / renal", search: [] },
  { code: "U07.1", diagnosis: "COVID-19", category: "Infectious", search: [] },
  { code: "A41.9", diagnosis: "Sepsis, unspecified organism", category: "Infectious", search: [] },
  { code: "F10.929", diagnosis: "Alcohol use, unspecified with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F41.9", diagnosis: "Anxiety disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F32.A", diagnosis: "Depression, unspecified", category: "Mental health / substance", search: [] },
  { code: "M54.50", diagnosis: "Low back pain, unspecified", category: "Musculoskeletal", search: [] },
  { code: "M25.561", diagnosis: "Pain in right knee", category: "Musculoskeletal", search: [] },
  { code: "R41.82", diagnosis: "Altered mental status, unspecified", category: "Neurological", search: [] },
  { code: "I63.9", diagnosis: "Cerebral infarction, unspecified", category: "Neurological", search: [] },
  { code: "R42", diagnosis: "Dizziness and giddiness", category: "Neurological", search: [] },
  { code: "G40.909", diagnosis: "Epilepsy, unspecified, not intractable, without status epilepticus", category: "Neurological", search: [] },
  { code: "R51.9", diagnosis: "Headache, unspecified", category: "Neurological", search: [] },
  { code: "R55", diagnosis: "Syncope and collapse", category: "Neurological", search: [] },
  { code: "G45.9", diagnosis: "Transient cerebral ischemic attack, unspecified", category: "Neurological", search: [] },
  { code: "O20.9", diagnosis: "Hemorrhage in early pregnancy, unspecified", category: "Obstetric", search: [] },
  { code: "O26.899", diagnosis: "Other specified pregnancy related conditions, unspecified trimester", category: "Obstetric", search: [] },
  { code: "J06.9", diagnosis: "Acute upper respiratory infection, unspecified", category: "Respiratory", search: [] },
  { code: "J44.1", diagnosis: "Chronic obstructive pulmonary disease with (acute) exacerbation", category: "Respiratory", search: [] },
  { code: "J18.9", diagnosis: "Pneumonia, unspecified organism", category: "Respiratory", search: [] },
  { code: "R06.02", diagnosis: "Shortness of breath", category: "Respiratory", search: [] },
  { code: "J45.901", diagnosis: "Unspecified asthma with (acute) exacerbation", category: "Respiratory", search: [] },
  { code: "L03.90", diagnosis: "Cellulitis, unspecified", category: "Skin / soft tissue", search: [] },
  { code: "L02.91", diagnosis: "Cutaneous abscess, unspecified", category: "Skin / soft tissue", search: [] },
  { code: "R07.9", diagnosis: "Chest pain, unspecified", category: "Symptoms / findings", search: [] },
  { code: "R50.9", diagnosis: "Fever, unspecified", category: "Symptoms / findings", search: [] },
  { code: "R53.1", diagnosis: "Weakness", category: "Symptoms / findings", search: [] },
  { code: "T78.40XA", diagnosis: "Allergy, unspecified, initial encounter", category: "Trauma / toxicology", search: [] },
  { code: "T78.2XXA", diagnosis: "Anaphylactic shock, unspecified, initial encounter", category: "Trauma / toxicology", search: [] },
  { code: "S06.0X0A", diagnosis: "Concussion without loss of consciousness, initial encounter", category: "Trauma / toxicology", search: [] },
  { code: "S01.81XA", diagnosis: "Laceration without foreign body of other part of head, initial encounter", category: "Trauma / toxicology", search: [] },
  { code: "S61.411A", diagnosis: "Laceration without foreign body of right hand, initial encounter", category: "Trauma / toxicology", search: [] },
  { code: "T50.901A", diagnosis: "Poisoning by unspecified drugs, medicaments and biological substances, accidental (unintentional), initial encounter", category: "Trauma / toxicology", search: [] },
  { code: "S52.501A", diagnosis: "Unspecified fracture of the lower end of right radius, initial encounter for closed fracture", category: "Trauma / toxicology", search: [] },
  { code: "S09.90XA", diagnosis: "Unspecified injury of head, initial encounter", category: "Trauma / toxicology", search: [] },
  { code: "I50.41", diagnosis: "Acute combined systolic (congestive) and diastolic (congestive) heart failure", category: "Cardiovascular", search: [] },
  { code: "I24.81", diagnosis: "Acute coronary microvascular dysfunction", category: "Cardiovascular", search: [] },
  { code: "I24.0", diagnosis: "Acute coronary thrombosis not resulting in myocardial infarction", category: "Cardiovascular", search: [] },
  { code: "I50.31", diagnosis: "Acute diastolic (congestive) heart failure", category: "Cardiovascular", search: [] },
  { code: "I24.9", diagnosis: "Acute ischemic heart disease, unspecified", category: "Cardiovascular", search: [] },
  { code: "I21.9", diagnosis: "Acute myocardial infarction, unspecified", category: "Cardiovascular", search: [] },
  { code: "I40.9", diagnosis: "Acute myocarditis, unspecified", category: "Cardiovascular", search: [] },
  { code: "I50.43", diagnosis: "Acute on chronic combined systolic (congestive) and diastolic (congestive) heart failure", category: "Cardiovascular", search: [] },
  { code: "I50.33", diagnosis: "Acute on chronic diastolic (congestive) heart failure", category: "Cardiovascular", search: [] },
  { code: "I50.813", diagnosis: "Acute on chronic right heart failure", category: "Cardiovascular", search: [] },
  { code: "I50.23", diagnosis: "Acute on chronic systolic (congestive) heart failure", category: "Cardiovascular", search: [] },
  { code: "I50.811", diagnosis: "Acute right heart failure", category: "Cardiovascular", search: [] },
  { code: "I50.21", diagnosis: "Acute systolic (congestive) heart failure", category: "Cardiovascular", search: [] },
  { code: "I25.729", diagnosis: "Atherosclerosis of autologous artery coronary artery bypass graft(s) with unspecified angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I25.719", diagnosis: "Atherosclerosis of autologous vein coronary artery bypass graft(s) with unspecified angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I25.769", diagnosis: "Atherosclerosis of bypass graft of coronary artery of transplanted heart with unspecified angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I25.701", diagnosis: "Atherosclerosis of coronary artery bypass graft(s), unspecified, with angina pectoris with documented spasm", category: "Cardiovascular", search: [] },
  { code: "I25.708", diagnosis: "Atherosclerosis of coronary artery bypass graft(s), unspecified, with other forms of angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I25.702", diagnosis: "Atherosclerosis of coronary artery bypass graft(s), unspecified, with refractory angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I25.709", diagnosis: "Atherosclerosis of coronary artery bypass graft(s), unspecified, with unspecified angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I25.700", diagnosis: "Atherosclerosis of coronary artery bypass graft(s), unspecified, with unstable angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I25.759", diagnosis: "Atherosclerosis of native coronary artery of transplanted heart with unspecified angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I25.739", diagnosis: "Atherosclerosis of nonautologous biological coronary artery bypass graft(s) with unspecified angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I25.799", diagnosis: "Atherosclerosis of other coronary artery bypass graft(s) with unspecified angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I25.119", diagnosis: "Atherosclerotic heart disease of native coronary artery with unspecified angina pectoris", category: "Cardiovascular", search: [] },
  { code: "I23.1", diagnosis: "Atrial septal defect as current complication following acute myocardial infarction", category: "Cardiovascular", search: [] },
  { code: "I46.9", diagnosis: "Cardiac arrest, cause unspecified", category: "Cardiovascular", search: [] },
  { code: "I49.9", diagnosis: "Cardiac arrhythmia, unspecified", category: "Cardiovascular", search: [] },
  { code: "I42.9", diagnosis: "Cardiomyopathy, unspecified", category: "Cardiovascular", search: [] },
  { code: "I26.03", diagnosis: "Cement embolism of pulmonary artery with acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I26.95", diagnosis: "Cement embolism of pulmonary artery without acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I48.20", diagnosis: "Chronic atrial fibrillation, unspecified", category: "Cardiovascular", search: [] },
  { code: "I25.9", diagnosis: "Chronic ischemic heart disease, unspecified", category: "Cardiovascular", search: [] },
  { code: "I45.9", diagnosis: "Conduction disorder, unspecified", category: "Cardiovascular", search: [] },
  { code: "I28.9", diagnosis: "Disease of pulmonary vessels, unspecified", category: "Cardiovascular", search: [] },
  { code: "I26.04", diagnosis: "Fat embolism of pulmonary artery with acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I26.96", diagnosis: "Fat embolism of pulmonary artery without acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I27.849", diagnosis: "Fontan related circulation, unspecified", category: "Cardiovascular", search: [] },
  { code: "I51.9", diagnosis: "Heart disease, unspecified", category: "Cardiovascular", search: [] },
  { code: "I23.0", diagnosis: "Hemopericardium as current complication following acute myocardial infarction", category: "Cardiovascular", search: [] },
  { code: "I12.9", diagnosis: "Hypertensive chronic kidney disease with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease", category: "Cardiovascular", search: [] },
  { code: "I16.9", diagnosis: "Hypertensive crisis, unspecified", category: "Cardiovascular", search: [] },
  { code: "I13.0", diagnosis: "Hypertensive heart and chronic kidney disease with heart failure and stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease", category: "Cardiovascular", search: [] },
  { code: "I13.10", diagnosis: "Hypertensive heart and chronic kidney disease without heart failure, with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease", category: "Cardiovascular", search: [] },
  { code: "I44.7", diagnosis: "Left bundle-branch block, unspecified", category: "Cardiovascular", search: [] },
  { code: "I50.1", diagnosis: "Left ventricular failure, unspecified", category: "Cardiovascular", search: [] },
  { code: "I26.94", diagnosis: "Multiple subsegmental thrombotic pulmonary emboli without acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I51.4", diagnosis: "Myocarditis, unspecified", category: "Cardiovascular", search: [] },
  { code: "I40.8", diagnosis: "Other acute myocarditis", category: "Cardiovascular", search: [] },
  { code: "I23.8", diagnosis: "Other current complications following acute myocardial infarction", category: "Cardiovascular", search: [] },
  { code: "I24.89", diagnosis: "Other forms of acute ischemic heart disease", category: "Cardiovascular", search: [] },
  { code: "I26.09", diagnosis: "Other pulmonary embolism with acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I26.99", diagnosis: "Other pulmonary embolism without acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I47.9", diagnosis: "Paroxysmal tachycardia, unspecified", category: "Cardiovascular", search: [] },
  { code: "I27.9", diagnosis: "Pulmonary heart disease, unspecified", category: "Cardiovascular", search: [] },
  { code: "I27.20", diagnosis: "Pulmonary hypertension, unspecified", category: "Cardiovascular", search: [] },
  { code: "I50.810", diagnosis: "Right heart failure, unspecified", category: "Cardiovascular", search: [] },
  { code: "I23.3", diagnosis: "Rupture of cardiac wall without hemopericardium as current complication following acute myocardial infarction", category: "Cardiovascular", search: [] },
  { code: "I23.4", diagnosis: "Rupture of chordae tendineae as current complication following acute myocardial infarction", category: "Cardiovascular", search: [] },
  { code: "I23.5", diagnosis: "Rupture of papillary muscle as current complication following acute myocardial infarction", category: "Cardiovascular", search: [] },
  { code: "I26.02", diagnosis: "Saddle embolus of pulmonary artery with acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I26.92", diagnosis: "Saddle embolus of pulmonary artery without acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I15.9", diagnosis: "Secondary hypertension, unspecified", category: "Cardiovascular", search: [] },
  { code: "I26.01", diagnosis: "Septic pulmonary embolism with acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I26.90", diagnosis: "Septic pulmonary embolism without acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I26.93", diagnosis: "Single subsegmental thrombotic pulmonary embolism without acute cor pulmonale", category: "Cardiovascular", search: [] },
  { code: "I21.3", diagnosis: "ST elevation (STEMI) myocardial infarction of unspecified site", category: "Cardiovascular", search: [] },
  { code: "I22.9", diagnosis: "Subsequent ST elevation (STEMI) myocardial infarction of unspecified site", category: "Cardiovascular", search: [] },
  { code: "I47.10", diagnosis: "Supraventricular tachycardia, unspecified", category: "Cardiovascular", search: [] },
  { code: "I23.6", diagnosis: "Thrombosis of atrium, auricular appendage, and ventricle as current complications following acute myocardial infarction", category: "Cardiovascular", search: [] },
  { code: "I48.92", diagnosis: "Unspecified atrial flutter", category: "Cardiovascular", search: [] },
  { code: "I44.30", diagnosis: "Unspecified atrioventricular block", category: "Cardiovascular", search: [] },
  { code: "I50.40", diagnosis: "Unspecified combined systolic (congestive) and diastolic (congestive) heart failure", category: "Cardiovascular", search: [] },
  { code: "I50.30", diagnosis: "Unspecified diastolic (congestive) heart failure", category: "Cardiovascular", search: [] },
  { code: "I44.60", diagnosis: "Unspecified fascicular block", category: "Cardiovascular", search: [] },
  { code: "I49.40", diagnosis: "Unspecified premature depolarization", category: "Cardiovascular", search: [] },
  { code: "I45.10", diagnosis: "Unspecified right bundle-branch block", category: "Cardiovascular", search: [] },
  { code: "I50.20", diagnosis: "Unspecified systolic (congestive) heart failure", category: "Cardiovascular", search: [] },
  { code: "I23.2", diagnosis: "Ventricular septal defect as current complication following acute myocardial infarction", category: "Cardiovascular", search: [] },
  { code: "I47.20", diagnosis: "Ventricular tachycardia, unspecified", category: "Cardiovascular", search: [] },
  { code: "E16.9", diagnosis: "Disorder of pancreatic internal secretion, unspecified", category: "Endocrine / metabolic", search: [] },
  { code: "E13.37X9", diagnosis: "Other specified diabetes mellitus with diabetic macular edema, resolved following treatment, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.40", diagnosis: "Other specified diabetes mellitus with diabetic neuropathy, unspecified", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3219", diagnosis: "Other specified diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3299", diagnosis: "Other specified diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3319", diagnosis: "Other specified diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3399", diagnosis: "Other specified diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3549", diagnosis: "Other specified diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3519", diagnosis: "Other specified diabetes mellitus with proliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3529", diagnosis: "Other specified diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3539", diagnosis: "Other specified diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3599", diagnosis: "Other specified diabetes mellitus with proliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3419", diagnosis: "Other specified diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3499", diagnosis: "Other specified diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.3559", diagnosis: "Other specified diabetes mellitus with stable proliferative diabetic retinopathy, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E13.8", diagnosis: "Other specified diabetes mellitus with unspecified complications", category: "Endocrine / metabolic", search: [] },
  { code: "E13.311", diagnosis: "Other specified diabetes mellitus with unspecified diabetic retinopathy with macular edema", category: "Endocrine / metabolic", search: [] },
  { code: "E13.319", diagnosis: "Other specified diabetes mellitus with unspecified diabetic retinopathy without macular edema", category: "Endocrine / metabolic", search: [] },
  { code: "E10.37X9", diagnosis: "Type 1 diabetes mellitus with diabetic macular edema, resolved following treatment, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.40", diagnosis: "Type 1 diabetes mellitus with diabetic neuropathy, unspecified", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3219", diagnosis: "Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3299", diagnosis: "Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3319", diagnosis: "Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3399", diagnosis: "Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3549", diagnosis: "Type 1 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3519", diagnosis: "Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3529", diagnosis: "Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3539", diagnosis: "Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3599", diagnosis: "Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3419", diagnosis: "Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3499", diagnosis: "Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.3559", diagnosis: "Type 1 diabetes mellitus with stable proliferative diabetic retinopathy, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E10.8", diagnosis: "Type 1 diabetes mellitus with unspecified complications", category: "Endocrine / metabolic", search: [] },
  { code: "E10.311", diagnosis: "Type 1 diabetes mellitus with unspecified diabetic retinopathy with macular edema", category: "Endocrine / metabolic", search: [] },
  { code: "E10.319", diagnosis: "Type 1 diabetes mellitus with unspecified diabetic retinopathy without macular edema", category: "Endocrine / metabolic", search: [] },
  { code: "E10.A0", diagnosis: "Type 1 diabetes mellitus, presymptomatic, unspecified", category: "Endocrine / metabolic", search: [] },
  { code: "E11.37X9", diagnosis: "Type 2 diabetes mellitus with diabetic macular edema, resolved following treatment, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.40", diagnosis: "Type 2 diabetes mellitus with diabetic neuropathy, unspecified", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3219", diagnosis: "Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3299", diagnosis: "Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3319", diagnosis: "Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3399", diagnosis: "Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3549", diagnosis: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3519", diagnosis: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3529", diagnosis: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3539", diagnosis: "Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3599", diagnosis: "Type 2 diabetes mellitus with proliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3419", diagnosis: "Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3499", diagnosis: "Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.3559", diagnosis: "Type 2 diabetes mellitus with stable proliferative diabetic retinopathy, unspecified eye", category: "Endocrine / metabolic", search: [] },
  { code: "E11.8", diagnosis: "Type 2 diabetes mellitus with unspecified complications", category: "Endocrine / metabolic", search: [] },
  { code: "E11.311", diagnosis: "Type 2 diabetes mellitus with unspecified diabetic retinopathy with macular edema", category: "Endocrine / metabolic", search: [] },
  { code: "E11.319", diagnosis: "Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema", category: "Endocrine / metabolic", search: [] },
  { code: "E86.9", diagnosis: "Volume depletion, unspecified", category: "Endocrine / metabolic", search: [] },
  { code: "R19.30", diagnosis: "Abdominal rigidity, unspecified site", category: "Gastrointestinal", search: [] },
  { code: "R10.819", diagnosis: "Abdominal tenderness, unspecified site", category: "Gastrointestinal", search: [] },
  { code: "K55.059", diagnosis: "Acute (reversible) ischemia of intestine, part and extent unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.039", diagnosis: "Acute (reversible) ischemia of large intestine, extent unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.019", diagnosis: "Acute (reversible) ischemia of small intestine, extent unspecified", category: "Gastrointestinal", search: [] },
  { code: "R10.0", diagnosis: "Acute abdomen", category: "Gastrointestinal", search: [] },
  { code: "K35.219", diagnosis: "Acute appendicitis with generalized peritonitis, with abscess, unspecified as to perforation", category: "Gastrointestinal", search: [] },
  { code: "K35.211", diagnosis: "Acute appendicitis with generalized peritonitis, with perforation and abscess", category: "Gastrointestinal", search: [] },
  { code: "K35.201", diagnosis: "Acute appendicitis with generalized peritonitis, with perforation, without abscess", category: "Gastrointestinal", search: [] },
  { code: "K35.209", diagnosis: "Acute appendicitis with generalized peritonitis, without abscess, unspecified as to perforation", category: "Gastrointestinal", search: [] },
  { code: "K35.200", diagnosis: "Acute appendicitis with generalized peritonitis, without perforation or abscess", category: "Gastrointestinal", search: [] },
  { code: "K35.210", diagnosis: "Acute appendicitis with generalized peritonitis, without perforation, with abscess", category: "Gastrointestinal", search: [] },
  { code: "K35.31", diagnosis: "Acute appendicitis with localized peritonitis and gangrene, without perforation", category: "Gastrointestinal", search: [] },
  { code: "K35.30", diagnosis: "Acute appendicitis with localized peritonitis, without perforation or gangrene", category: "Gastrointestinal", search: [] },
  { code: "K35.33", diagnosis: "Acute appendicitis with perforation, localized peritonitis, and gangrene, with abscess", category: "Gastrointestinal", search: [] },
  { code: "K35.32", diagnosis: "Acute appendicitis with perforation, localized peritonitis, and gangrene, without abscess", category: "Gastrointestinal", search: [] },
  { code: "K81.0", diagnosis: "Acute cholecystitis", category: "Gastrointestinal", search: [] },
  { code: "K81.2", diagnosis: "Acute cholecystitis with chronic cholecystitis", category: "Gastrointestinal", search: [] },
  { code: "K31.0", diagnosis: "Acute dilatation of stomach", category: "Gastrointestinal", search: [] },
  { code: "K55.069", diagnosis: "Acute infarction of intestine, part and extent unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.049", diagnosis: "Acute infarction of large intestine, extent unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.029", diagnosis: "Acute infarction of small intestine, extent unspecified", category: "Gastrointestinal", search: [] },
  { code: "K85.92", diagnosis: "Acute pancreatitis with infected necrosis, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K85.91", diagnosis: "Acute pancreatitis with uninfected necrosis, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K85.90", diagnosis: "Acute pancreatitis without necrosis or infection, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K85.22", diagnosis: "Alcohol induced acute pancreatitis with infected necrosis", category: "Gastrointestinal", search: [] },
  { code: "K85.21", diagnosis: "Alcohol induced acute pancreatitis with uninfected necrosis", category: "Gastrointestinal", search: [] },
  { code: "K85.20", diagnosis: "Alcohol induced acute pancreatitis without necrosis or infection", category: "Gastrointestinal", search: [] },
  { code: "K85.12", diagnosis: "Biliary acute pancreatitis with infected necrosis", category: "Gastrointestinal", search: [] },
  { code: "K85.11", diagnosis: "Biliary acute pancreatitis with uninfected necrosis", category: "Gastrointestinal", search: [] },
  { code: "K85.10", diagnosis: "Biliary acute pancreatitis without necrosis or infection", category: "Gastrointestinal", search: [] },
  { code: "K80.37", diagnosis: "Calculus of bile duct with acute and chronic cholangitis with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.36", diagnosis: "Calculus of bile duct with acute and chronic cholangitis without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.47", diagnosis: "Calculus of bile duct with acute and chronic cholecystitis with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.46", diagnosis: "Calculus of bile duct with acute and chronic cholecystitis without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.33", diagnosis: "Calculus of bile duct with acute cholangitis with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.32", diagnosis: "Calculus of bile duct with acute cholangitis without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.43", diagnosis: "Calculus of bile duct with acute cholecystitis with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.42", diagnosis: "Calculus of bile duct with acute cholecystitis without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.31", diagnosis: "Calculus of bile duct with cholangitis, unspecified, with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.30", diagnosis: "Calculus of bile duct with cholangitis, unspecified, without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.41", diagnosis: "Calculus of bile duct with cholecystitis, unspecified, with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.40", diagnosis: "Calculus of bile duct with cholecystitis, unspecified, without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.67", diagnosis: "Calculus of gallbladder and bile duct with acute and chronic cholecystitis with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.66", diagnosis: "Calculus of gallbladder and bile duct with acute and chronic cholecystitis without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.63", diagnosis: "Calculus of gallbladder and bile duct with acute cholecystitis with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.62", diagnosis: "Calculus of gallbladder and bile duct with acute cholecystitis without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.61", diagnosis: "Calculus of gallbladder and bile duct with cholecystitis, unspecified, with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.60", diagnosis: "Calculus of gallbladder and bile duct with cholecystitis, unspecified, without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.13", diagnosis: "Calculus of gallbladder with acute and chronic cholecystitis with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.12", diagnosis: "Calculus of gallbladder with acute and chronic cholecystitis without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.01", diagnosis: "Calculus of gallbladder with acute cholecystitis with obstruction", category: "Gastrointestinal", search: [] },
  { code: "K80.00", diagnosis: "Calculus of gallbladder with acute cholecystitis without obstruction", category: "Gastrointestinal", search: [] },
  { code: "K81.9", diagnosis: "Cholecystitis, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K56.601", diagnosis: "Complete intestinal obstruction, unspecified as to cause", category: "Gastrointestinal", search: [] },
  { code: "K59.00", diagnosis: "Constipation, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K50.819", diagnosis: "Crohn's disease of both small and large intestine with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "K50.119", diagnosis: "Crohn's disease of large intestine with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "K50.019", diagnosis: "Crohn's disease of small intestine with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "K50.914", diagnosis: "Crohn's disease, unspecified, with abscess", category: "Gastrointestinal", search: [] },
  { code: "K50.913", diagnosis: "Crohn's disease, unspecified, with fistula", category: "Gastrointestinal", search: [] },
  { code: "K50.912", diagnosis: "Crohn's disease, unspecified, with intestinal obstruction", category: "Gastrointestinal", search: [] },
  { code: "K50.918", diagnosis: "Crohn's disease, unspecified, with other complication", category: "Gastrointestinal", search: [] },
  { code: "K50.911", diagnosis: "Crohn's disease, unspecified, with rectal bleeding", category: "Gastrointestinal", search: [] },
  { code: "K50.919", diagnosis: "Crohn's disease, unspecified, with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "K50.90", diagnosis: "Crohn's disease, unspecified, without complications", category: "Gastrointestinal", search: [] },
  { code: "K55.052", diagnosis: "Diffuse acute (reversible) ischemia of intestine, part unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.032", diagnosis: "Diffuse acute (reversible) ischemia of large intestine", category: "Gastrointestinal", search: [] },
  { code: "K55.012", diagnosis: "Diffuse acute (reversible) ischemia of small intestine", category: "Gastrointestinal", search: [] },
  { code: "K55.062", diagnosis: "Diffuse acute infarction of intestine, part unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.042", diagnosis: "Diffuse acute infarction of large intestine", category: "Gastrointestinal", search: [] },
  { code: "K55.022", diagnosis: "Diffuse acute infarction of small intestine", category: "Gastrointestinal", search: [] },
  { code: "K38.9", diagnosis: "Disease of appendix, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K83.9", diagnosis: "Disease of biliary tract, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K82.9", diagnosis: "Disease of gallbladder, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K86.9", diagnosis: "Disease of pancreas, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K31.9", diagnosis: "Disease of stomach and duodenum, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K57.81", diagnosis: "Diverticulitis of intestine, part unspecified, with perforation and abscess with bleeding", category: "Gastrointestinal", search: [] },
  { code: "K57.80", diagnosis: "Diverticulitis of intestine, part unspecified, with perforation and abscess without bleeding", category: "Gastrointestinal", search: [] },
  { code: "K57.93", diagnosis: "Diverticulitis of intestine, part unspecified, without perforation or abscess with bleeding", category: "Gastrointestinal", search: [] },
  { code: "K57.92", diagnosis: "Diverticulitis of intestine, part unspecified, without perforation or abscess without bleeding", category: "Gastrointestinal", search: [] },
  { code: "K57.91", diagnosis: "Diverticulosis of intestine, part unspecified, without perforation or abscess with bleeding", category: "Gastrointestinal", search: [] },
  { code: "K57.90", diagnosis: "Diverticulosis of intestine, part unspecified, without perforation or abscess without bleeding", category: "Gastrointestinal", search: [] },
  { code: "K85.32", diagnosis: "Drug induced acute pancreatitis with infected necrosis", category: "Gastrointestinal", search: [] },
  { code: "K85.31", diagnosis: "Drug induced acute pancreatitis with uninfected necrosis", category: "Gastrointestinal", search: [] },
  { code: "K85.30", diagnosis: "Drug induced acute pancreatitis without necrosis or infection", category: "Gastrointestinal", search: [] },
  { code: "R13.10", diagnosis: "Dysphagia, unspecified", category: "Gastrointestinal", search: [] },
  { code: "R10.A0", diagnosis: "Flank pain, unspecified side", category: "Gastrointestinal", search: [] },
  { code: "R10.8A9", diagnosis: "Flank tenderness, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.051", diagnosis: "Focal (segmental) acute (reversible) ischemia of intestine, part unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.031", diagnosis: "Focal (segmental) acute (reversible) ischemia of large intestine", category: "Gastrointestinal", search: [] },
  { code: "K55.011", diagnosis: "Focal (segmental) acute (reversible) ischemia of small intestine", category: "Gastrointestinal", search: [] },
  { code: "K55.061", diagnosis: "Focal (segmental) acute infarction of intestine, part unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.041", diagnosis: "Focal (segmental) acute infarction of large intestine", category: "Gastrointestinal", search: [] },
  { code: "K55.021", diagnosis: "Focal (segmental) acute infarction of small intestine", category: "Gastrointestinal", search: [] },
  { code: "K59.9", diagnosis: "Functional intestinal disorder, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K31.A29", diagnosis: "Gastric intestinal metaplasia with dysplasia, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K31.A19", diagnosis: "Gastric intestinal metaplasia without dysplasia, unspecified site", category: "Gastrointestinal", search: [] },
  { code: "K31.A0", diagnosis: "Gastric intestinal metaplasia, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K85.02", diagnosis: "Idiopathic acute pancreatitis with infected necrosis", category: "Gastrointestinal", search: [] },
  { code: "K85.01", diagnosis: "Idiopathic acute pancreatitis with uninfected necrosis", category: "Gastrointestinal", search: [] },
  { code: "K85.00", diagnosis: "Idiopathic acute pancreatitis without necrosis or infection", category: "Gastrointestinal", search: [] },
  { code: "K56.7", diagnosis: "Ileus, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K51.419", diagnosis: "Inflammatory polyps of colon with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "K56.50", diagnosis: "Intestinal adhesions [bands], unspecified as to partial versus complete obstruction", category: "Gastrointestinal", search: [] },
  { code: "R19.00", diagnosis: "Intra-abdominal and pelvic swelling, mass and lump, unspecified site", category: "Gastrointestinal", search: [] },
  { code: "K58.9", diagnosis: "Irritable bowel syndrome, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K51.519", diagnosis: "Left sided colitis with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "R10.30", diagnosis: "Lower abdominal pain, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K52.839", diagnosis: "Microscopic colitis, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.30", diagnosis: "Necrotizing enterocolitis, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K35.890", diagnosis: "Other acute appendicitis without perforation or gangrene", category: "Gastrointestinal", search: [] },
  { code: "K35.891", diagnosis: "Other acute appendicitis without perforation, with gangrene", category: "Gastrointestinal", search: [] },
  { code: "K85.82", diagnosis: "Other acute pancreatitis with infected necrosis", category: "Gastrointestinal", search: [] },
  { code: "K85.81", diagnosis: "Other acute pancreatitis with uninfected necrosis", category: "Gastrointestinal", search: [] },
  { code: "K85.80", diagnosis: "Other acute pancreatitis without necrosis or infection", category: "Gastrointestinal", search: [] },
  { code: "K56.699", diagnosis: "Other intestinal obstruction unspecified as to partial versus complete obstruction", category: "Gastrointestinal", search: [] },
  { code: "K51.819", diagnosis: "Other ulcerative colitis with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "K56.600", diagnosis: "Partial intestinal obstruction, unspecified as to cause", category: "Gastrointestinal", search: [] },
  { code: "R10.20", diagnosis: "Pelvic and perineal pain unspecified side", category: "Gastrointestinal", search: [] },
  { code: "R10.829", diagnosis: "Rebound abdominal tenderness, unspecified site", category: "Gastrointestinal", search: [] },
  { code: "K51.019", diagnosis: "Ulcerative (chronic) pancolitis with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "K51.219", diagnosis: "Ulcerative (chronic) proctitis with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "K51.319", diagnosis: "Ulcerative (chronic) rectosigmoiditis with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "K51.914", diagnosis: "Ulcerative colitis, unspecified with abscess", category: "Gastrointestinal", search: [] },
  { code: "K51.913", diagnosis: "Ulcerative colitis, unspecified with fistula", category: "Gastrointestinal", search: [] },
  { code: "K51.912", diagnosis: "Ulcerative colitis, unspecified with intestinal obstruction", category: "Gastrointestinal", search: [] },
  { code: "K51.918", diagnosis: "Ulcerative colitis, unspecified with other complication", category: "Gastrointestinal", search: [] },
  { code: "K51.911", diagnosis: "Ulcerative colitis, unspecified with rectal bleeding", category: "Gastrointestinal", search: [] },
  { code: "K51.919", diagnosis: "Ulcerative colitis, unspecified with unspecified complications", category: "Gastrointestinal", search: [] },
  { code: "K51.90", diagnosis: "Ulcerative colitis, unspecified, without complications", category: "Gastrointestinal", search: [] },
  { code: "K37", diagnosis: "Unspecified appendicitis", category: "Gastrointestinal", search: [] },
  { code: "K56.609", diagnosis: "Unspecified intestinal obstruction, unspecified as to partial versus complete obstruction", category: "Gastrointestinal", search: [] },
  { code: "R17", diagnosis: "Unspecified jaundice", category: "Gastrointestinal", search: [] },
  { code: "R10.10", diagnosis: "Upper abdominal pain, unspecified", category: "Gastrointestinal", search: [] },
  { code: "K55.9", diagnosis: "Vascular disorder of intestine, unspecified", category: "Gastrointestinal", search: [] },
  { code: "R11.10", diagnosis: "Vomiting, unspecified", category: "Gastrointestinal", search: [] },
  { code: "N30.01", diagnosis: "Acute cystitis with hematuria", category: "Genitourinary / renal", search: [] },
  { code: "N17.1", diagnosis: "Acute kidney failure with acute cortical necrosis", category: "Genitourinary / renal", search: [] },
  { code: "N17.2", diagnosis: "Acute kidney failure with medullary necrosis", category: "Genitourinary / renal", search: [] },
  { code: "N17.0", diagnosis: "Acute kidney failure with tubular necrosis", category: "Genitourinary / renal", search: [] },
  { code: "N10", diagnosis: "Acute pyelonephritis", category: "Genitourinary / renal", search: [] },
  { code: "N32.9", diagnosis: "Bladder disorder, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N21.9", diagnosis: "Calculus of lower urinary tract, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N18.30", diagnosis: "Chronic kidney disease, stage 3 unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N18.9", diagnosis: "Chronic kidney disease, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N11.9", diagnosis: "Chronic tubulo-interstitial nephritis, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "R39.859", diagnosis: "Costovertebral (angle) tenderness, unspecified side", category: "Genitourinary / renal", search: [] },
  { code: "N30.91", diagnosis: "Cystitis, unspecified with hematuria", category: "Genitourinary / renal", search: [] },
  { code: "N30.90", diagnosis: "Cystitis, unspecified without hematuria", category: "Genitourinary / renal", search: [] },
  { code: "N28.9", diagnosis: "Disorder of kidney and ureter, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N39.9", diagnosis: "Disorder of urinary system, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N25.9", diagnosis: "Disorder resulting from impaired renal tubular function, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "R31.9", diagnosis: "Hematuria, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N14.2", diagnosis: "Nephropathy induced by unspecified drug, medicament or biological substance", category: "Genitourinary / renal", search: [] },
  { code: "N31.9", diagnosis: "Neuromuscular dysfunction of bladder, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N13.9", diagnosis: "Obstructive and reflux uropathy, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N17.8", diagnosis: "Other acute kidney failure", category: "Genitourinary / renal", search: [] },
  { code: "N35.819", diagnosis: "Other urethral stricture, male, unspecified site", category: "Genitourinary / renal", search: [] },
  { code: "R30.9", diagnosis: "Painful micturition, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N35.119", diagnosis: "Postinfective urethral stricture, not elsewhere classified, male, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N35.014", diagnosis: "Post-traumatic urethral stricture, male, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N26.9", diagnosis: "Renal sclerosis, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N15.9", diagnosis: "Renal tubulo-interstitial disease, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "R33.9", diagnosis: "Retention of urine, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "R37", diagnosis: "Sexual dysfunction, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N27.9", diagnosis: "Small kidney, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N12", diagnosis: "Tubulo-interstitial nephritis, not specified as acute or chronic", category: "Genitourinary / renal", search: [] },
  { code: "N35.914", diagnosis: "Unspecified anterior urethral stricture, male", category: "Genitourinary / renal", search: [] },
  { code: "N35.912", diagnosis: "Unspecified bulbous urethral stricture, male", category: "Genitourinary / renal", search: [] },
  { code: "N13.30", diagnosis: "Unspecified hydronephrosis", category: "Genitourinary / renal", search: [] },
  { code: "N19", diagnosis: "Unspecified kidney failure", category: "Genitourinary / renal", search: [] },
  { code: "N35.913", diagnosis: "Unspecified membranous urethral stricture, male", category: "Genitourinary / renal", search: [] },
  { code: "N23", diagnosis: "Unspecified renal colic", category: "Genitourinary / renal", search: [] },
  { code: "R39.9", diagnosis: "Unspecified symptoms and signs involving the genitourinary system", category: "Genitourinary / renal", search: [] },
  { code: "N35.92", diagnosis: "Unspecified urethral stricture, female", category: "Genitourinary / renal", search: [] },
  { code: "N35.911", diagnosis: "Unspecified urethral stricture, male, meatal", category: "Genitourinary / renal", search: [] },
  { code: "N35.916", diagnosis: "Unspecified urethral stricture, male, overlapping sites", category: "Genitourinary / renal", search: [] },
  { code: "N35.919", diagnosis: "Unspecified urethral stricture, male, unspecified site", category: "Genitourinary / renal", search: [] },
  { code: "R32", diagnosis: "Unspecified urinary incontinence", category: "Genitourinary / renal", search: [] },
  { code: "R36.9", diagnosis: "Urethral discharge, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N36.9", diagnosis: "Urethral disorder, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N34.3", diagnosis: "Urethral syndrome, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N20.9", diagnosis: "Urinary calculus, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N13.739", diagnosis: "Vesicoureteral-reflux with reflux nephropathy with hydroureter, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N13.729", diagnosis: "Vesicoureteral-reflux with reflux nephropathy without hydroureter, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "N13.70", diagnosis: "Vesicoureteral-reflux, unspecified", category: "Genitourinary / renal", search: [] },
  { code: "A42.9", diagnosis: "Actinomycosis, unspecified", category: "Infectious", search: [] },
  { code: "B34.0", diagnosis: "Adenovirus infection, unspecified", category: "Infectious", search: [] },
  { code: "A49.9", diagnosis: "Bacterial infection, unspecified", category: "Infectious", search: [] },
  { code: "A44.9", diagnosis: "Bartonellosis, unspecified", category: "Infectious", search: [] },
  { code: "B34.2", diagnosis: "Coronavirus infection, unspecified", category: "Infectious", search: [] },
  { code: "B34.1", diagnosis: "Enterovirus infection, unspecified", category: "Infectious", search: [] },
  { code: "A41.50", diagnosis: "Gram-negative sepsis, unspecified", category: "Infectious", search: [] },
  { code: "A49.2", diagnosis: "Hemophilus influenzae infection, unspecified site", category: "Infectious", search: [] },
  { code: "A49.02", diagnosis: "Methicillin resistant Staphylococcus aureus infection, unspecified site", category: "Infectious", search: [] },
  { code: "A49.01", diagnosis: "Methicillin susceptible Staphylococcus aureus infection, unspecified site", category: "Infectious", search: [] },
  { code: "A49.3", diagnosis: "Mycoplasma infection, unspecified site", category: "Infectious", search: [] },
  { code: "A43.9", diagnosis: "Nocardiosis, unspecified", category: "Infectious", search: [] },
  { code: "A49.8", diagnosis: "Other bacterial infections of unspecified site", category: "Infectious", search: [] },
  { code: "B34.8", diagnosis: "Other viral infections of unspecified site", category: "Infectious", search: [] },
  { code: "B34.4", diagnosis: "Papovavirus infection, unspecified", category: "Infectious", search: [] },
  { code: "B34.3", diagnosis: "Parvovirus infection, unspecified", category: "Infectious", search: [] },
  { code: "A41.2", diagnosis: "Sepsis due to unspecified staphylococcus", category: "Infectious", search: [] },
  { code: "A49.1", diagnosis: "Streptococcal infection, unspecified site", category: "Infectious", search: [] },
  { code: "A40.9", diagnosis: "Streptococcal sepsis, unspecified", category: "Infectious", search: [] },
  { code: "B34.9", diagnosis: "Viral infection, unspecified", category: "Infectious", search: [] },
  { code: "F43.0", diagnosis: "Acute stress reaction", category: "Mental health / substance", search: [] },
  { code: "F43.20", diagnosis: "Adjustment disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F40.00", diagnosis: "Agoraphobia, unspecified", category: "Mental health / substance", search: [] },
  { code: "F10.159", diagnosis: "Alcohol abuse with alcohol-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F10.129", diagnosis: "Alcohol abuse with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F10.19", diagnosis: "Alcohol abuse with unspecified alcohol-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F10.139", diagnosis: "Alcohol abuse with withdrawal, unspecified", category: "Mental health / substance", search: [] },
  { code: "F10.259", diagnosis: "Alcohol dependence with alcohol-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F10.229", diagnosis: "Alcohol dependence with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F10.29", diagnosis: "Alcohol dependence with unspecified alcohol-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F10.239", diagnosis: "Alcohol dependence with withdrawal, unspecified", category: "Mental health / substance", search: [] },
  { code: "F10.980", diagnosis: "Alcohol use, unspecified with alcohol-induced anxiety disorder", category: "Mental health / substance", search: [] },
  { code: "F10.94", diagnosis: "Alcohol use, unspecified with alcohol-induced mood disorder", category: "Mental health / substance", search: [] },
  { code: "F10.96", diagnosis: "Alcohol use, unspecified with alcohol-induced persisting amnestic disorder", category: "Mental health / substance", search: [] },
  { code: "F10.97", diagnosis: "Alcohol use, unspecified with alcohol-induced persisting dementia", category: "Mental health / substance", search: [] },
  { code: "F10.950", diagnosis: "Alcohol use, unspecified with alcohol-induced psychotic disorder with delusions", category: "Mental health / substance", search: [] },
  { code: "F10.951", diagnosis: "Alcohol use, unspecified with alcohol-induced psychotic disorder with hallucinations", category: "Mental health / substance", search: [] },
  { code: "F10.959", diagnosis: "Alcohol use, unspecified with alcohol-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F10.981", diagnosis: "Alcohol use, unspecified with alcohol-induced sexual dysfunction", category: "Mental health / substance", search: [] },
  { code: "F10.982", diagnosis: "Alcohol use, unspecified with alcohol-induced sleep disorder", category: "Mental health / substance", search: [] },
  { code: "F10.921", diagnosis: "Alcohol use, unspecified with intoxication delirium", category: "Mental health / substance", search: [] },
  { code: "F10.920", diagnosis: "Alcohol use, unspecified with intoxication, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F10.988", diagnosis: "Alcohol use, unspecified with other alcohol-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F10.99", diagnosis: "Alcohol use, unspecified with unspecified alcohol-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F10.931", diagnosis: "Alcohol use, unspecified with withdrawal delirium", category: "Mental health / substance", search: [] },
  { code: "F10.932", diagnosis: "Alcohol use, unspecified with withdrawal with perceptual disturbance", category: "Mental health / substance", search: [] },
  { code: "F10.930", diagnosis: "Alcohol use, unspecified with withdrawal, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F10.939", diagnosis: "Alcohol use, unspecified with withdrawal, unspecified", category: "Mental health / substance", search: [] },
  { code: "F10.91", diagnosis: "Alcohol use, unspecified, in remission", category: "Mental health / substance", search: [] },
  { code: "F10.90", diagnosis: "Alcohol use, unspecified, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F31.30", diagnosis: "Bipolar disorder, current episode depressed, mild or moderate severity, unspecified", category: "Mental health / substance", search: [] },
  { code: "F31.10", diagnosis: "Bipolar disorder, current episode manic without psychotic features, unspecified", category: "Mental health / substance", search: [] },
  { code: "F31.60", diagnosis: "Bipolar disorder, current episode mixed, unspecified", category: "Mental health / substance", search: [] },
  { code: "F31.70", diagnosis: "Bipolar disorder, currently in remission, most recent episode unspecified", category: "Mental health / substance", search: [] },
  { code: "F31.9", diagnosis: "Bipolar disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F12.129", diagnosis: "Cannabis abuse with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F12.159", diagnosis: "Cannabis abuse with psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F12.19", diagnosis: "Cannabis abuse with unspecified cannabis-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F12.229", diagnosis: "Cannabis dependence with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F12.259", diagnosis: "Cannabis dependence with psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F12.29", diagnosis: "Cannabis dependence with unspecified cannabis-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F12.980", diagnosis: "Cannabis use, unspecified with anxiety disorder", category: "Mental health / substance", search: [] },
  { code: "F12.921", diagnosis: "Cannabis use, unspecified with intoxication delirium", category: "Mental health / substance", search: [] },
  { code: "F12.922", diagnosis: "Cannabis use, unspecified with intoxication with perceptual disturbance", category: "Mental health / substance", search: [] },
  { code: "F12.920", diagnosis: "Cannabis use, unspecified with intoxication, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F12.929", diagnosis: "Cannabis use, unspecified with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F12.988", diagnosis: "Cannabis use, unspecified with other cannabis-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F12.950", diagnosis: "Cannabis use, unspecified with psychotic disorder with delusions", category: "Mental health / substance", search: [] },
  { code: "F12.951", diagnosis: "Cannabis use, unspecified with psychotic disorder with hallucinations", category: "Mental health / substance", search: [] },
  { code: "F12.959", diagnosis: "Cannabis use, unspecified with psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F12.99", diagnosis: "Cannabis use, unspecified with unspecified cannabis-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F12.93", diagnosis: "Cannabis use, unspecified with withdrawal", category: "Mental health / substance", search: [] },
  { code: "F12.91", diagnosis: "Cannabis use, unspecified, in remission", category: "Mental health / substance", search: [] },
  { code: "F12.90", diagnosis: "Cannabis use, unspecified, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F14.159", diagnosis: "Cocaine abuse with cocaine-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F14.129", diagnosis: "Cocaine abuse with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F14.19", diagnosis: "Cocaine abuse with unspecified cocaine-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F14.13", diagnosis: "Cocaine abuse, unspecified with withdrawal", category: "Mental health / substance", search: [] },
  { code: "F14.259", diagnosis: "Cocaine dependence with cocaine-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F14.229", diagnosis: "Cocaine dependence with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F14.29", diagnosis: "Cocaine dependence with unspecified cocaine-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F14.980", diagnosis: "Cocaine use, unspecified with cocaine-induced anxiety disorder", category: "Mental health / substance", search: [] },
  { code: "F14.94", diagnosis: "Cocaine use, unspecified with cocaine-induced mood disorder", category: "Mental health / substance", search: [] },
  { code: "F14.950", diagnosis: "Cocaine use, unspecified with cocaine-induced psychotic disorder with delusions", category: "Mental health / substance", search: [] },
  { code: "F14.951", diagnosis: "Cocaine use, unspecified with cocaine-induced psychotic disorder with hallucinations", category: "Mental health / substance", search: [] },
  { code: "F14.959", diagnosis: "Cocaine use, unspecified with cocaine-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F14.981", diagnosis: "Cocaine use, unspecified with cocaine-induced sexual dysfunction", category: "Mental health / substance", search: [] },
  { code: "F14.982", diagnosis: "Cocaine use, unspecified with cocaine-induced sleep disorder", category: "Mental health / substance", search: [] },
  { code: "F14.921", diagnosis: "Cocaine use, unspecified with intoxication delirium", category: "Mental health / substance", search: [] },
  { code: "F14.922", diagnosis: "Cocaine use, unspecified with intoxication with perceptual disturbance", category: "Mental health / substance", search: [] },
  { code: "F14.920", diagnosis: "Cocaine use, unspecified with intoxication, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F14.929", diagnosis: "Cocaine use, unspecified with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F14.988", diagnosis: "Cocaine use, unspecified with other cocaine-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F14.99", diagnosis: "Cocaine use, unspecified with unspecified cocaine-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F14.93", diagnosis: "Cocaine use, unspecified with withdrawal", category: "Mental health / substance", search: [] },
  { code: "F14.91", diagnosis: "Cocaine use, unspecified, in remission", category: "Mental health / substance", search: [] },
  { code: "F14.90", diagnosis: "Cocaine use, unspecified, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F44.9", diagnosis: "Dissociative and conversion disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F16.159", diagnosis: "Hallucinogen abuse with hallucinogen-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F16.129", diagnosis: "Hallucinogen abuse with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F16.19", diagnosis: "Hallucinogen abuse with unspecified hallucinogen-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F16.259", diagnosis: "Hallucinogen dependence with hallucinogen-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F16.229", diagnosis: "Hallucinogen dependence with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F16.29", diagnosis: "Hallucinogen dependence with unspecified hallucinogen-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F16.983", diagnosis: "Hallucinogen use, unspecified with hallucinogen persisting perception disorder (flashbacks)", category: "Mental health / substance", search: [] },
  { code: "F16.980", diagnosis: "Hallucinogen use, unspecified with hallucinogen-induced anxiety disorder", category: "Mental health / substance", search: [] },
  { code: "F16.94", diagnosis: "Hallucinogen use, unspecified with hallucinogen-induced mood disorder", category: "Mental health / substance", search: [] },
  { code: "F16.950", diagnosis: "Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder with delusions", category: "Mental health / substance", search: [] },
  { code: "F16.951", diagnosis: "Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder with hallucinations", category: "Mental health / substance", search: [] },
  { code: "F16.959", diagnosis: "Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F16.921", diagnosis: "Hallucinogen use, unspecified with intoxication with delirium", category: "Mental health / substance", search: [] },
  { code: "F16.920", diagnosis: "Hallucinogen use, unspecified with intoxication, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F16.929", diagnosis: "Hallucinogen use, unspecified with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F16.988", diagnosis: "Hallucinogen use, unspecified with other hallucinogen-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F16.99", diagnosis: "Hallucinogen use, unspecified with unspecified hallucinogen-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F16.91", diagnosis: "Hallucinogen use, unspecified, in remission", category: "Mental health / substance", search: [] },
  { code: "F16.90", diagnosis: "Hallucinogen use, unspecified, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F45.20", diagnosis: "Hypochondriacal disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F18.159", diagnosis: "Inhalant abuse with inhalant-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F18.129", diagnosis: "Inhalant abuse with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F18.19", diagnosis: "Inhalant abuse with unspecified inhalant-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F18.259", diagnosis: "Inhalant dependence with inhalant-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F18.229", diagnosis: "Inhalant dependence with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F18.29", diagnosis: "Inhalant dependence with unspecified inhalant-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F18.980", diagnosis: "Inhalant use, unspecified with inhalant-induced anxiety disorder", category: "Mental health / substance", search: [] },
  { code: "F18.94", diagnosis: "Inhalant use, unspecified with inhalant-induced mood disorder", category: "Mental health / substance", search: [] },
  { code: "F18.97", diagnosis: "Inhalant use, unspecified with inhalant-induced persisting dementia", category: "Mental health / substance", search: [] },
  { code: "F18.950", diagnosis: "Inhalant use, unspecified with inhalant-induced psychotic disorder with delusions", category: "Mental health / substance", search: [] },
  { code: "F18.951", diagnosis: "Inhalant use, unspecified with inhalant-induced psychotic disorder with hallucinations", category: "Mental health / substance", search: [] },
  { code: "F18.959", diagnosis: "Inhalant use, unspecified with inhalant-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F18.921", diagnosis: "Inhalant use, unspecified with intoxication with delirium", category: "Mental health / substance", search: [] },
  { code: "F18.920", diagnosis: "Inhalant use, unspecified with intoxication, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F18.929", diagnosis: "Inhalant use, unspecified with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F18.988", diagnosis: "Inhalant use, unspecified with other inhalant-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F18.99", diagnosis: "Inhalant use, unspecified with unspecified inhalant-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F18.91", diagnosis: "Inhalant use, unspecified, in remission", category: "Mental health / substance", search: [] },
  { code: "F18.90", diagnosis: "Inhalant use, unspecified, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F33.40", diagnosis: "Major depressive disorder, recurrent, in remission, unspecified", category: "Mental health / substance", search: [] },
  { code: "F33.9", diagnosis: "Major depressive disorder, recurrent, unspecified", category: "Mental health / substance", search: [] },
  { code: "F32.9", diagnosis: "Major depressive disorder, single episode, unspecified", category: "Mental health / substance", search: [] },
  { code: "F30.10", diagnosis: "Manic episode without psychotic symptoms, unspecified", category: "Mental health / substance", search: [] },
  { code: "F30.9", diagnosis: "Manic episode, unspecified", category: "Mental health / substance", search: [] },
  { code: "F17.203", diagnosis: "Nicotine dependence unspecified, with withdrawal", category: "Mental health / substance", search: [] },
  { code: "F17.229", diagnosis: "Nicotine dependence, chewing tobacco, with unspecified nicotine-induced disorders", category: "Mental health / substance", search: [] },
  { code: "F17.219", diagnosis: "Nicotine dependence, cigarettes, with unspecified nicotine-induced disorders", category: "Mental health / substance", search: [] },
  { code: "F17.299", diagnosis: "Nicotine dependence, other tobacco product, with unspecified nicotine-induced disorders", category: "Mental health / substance", search: [] },
  { code: "F17.201", diagnosis: "Nicotine dependence, unspecified, in remission", category: "Mental health / substance", search: [] },
  { code: "F17.200", diagnosis: "Nicotine dependence, unspecified, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F17.208", diagnosis: "Nicotine dependence, unspecified, with other nicotine-induced disorders", category: "Mental health / substance", search: [] },
  { code: "F17.209", diagnosis: "Nicotine dependence, unspecified, with unspecified nicotine-induced disorders", category: "Mental health / substance", search: [] },
  { code: "F48.9", diagnosis: "Nonpsychotic mental disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F42.9", diagnosis: "Obsessive-compulsive disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F11.129", diagnosis: "Opioid abuse with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F11.159", diagnosis: "Opioid abuse with opioid-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F11.19", diagnosis: "Opioid abuse with unspecified opioid-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F11.229", diagnosis: "Opioid dependence with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F11.259", diagnosis: "Opioid dependence with opioid-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F11.29", diagnosis: "Opioid dependence with unspecified opioid-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F11.921", diagnosis: "Opioid use, unspecified with intoxication delirium", category: "Mental health / substance", search: [] },
  { code: "F11.922", diagnosis: "Opioid use, unspecified with intoxication with perceptual disturbance", category: "Mental health / substance", search: [] },
  { code: "F11.920", diagnosis: "Opioid use, unspecified with intoxication, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F11.929", diagnosis: "Opioid use, unspecified with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F11.94", diagnosis: "Opioid use, unspecified with opioid-induced mood disorder", category: "Mental health / substance", search: [] },
  { code: "F11.950", diagnosis: "Opioid use, unspecified with opioid-induced psychotic disorder with delusions", category: "Mental health / substance", search: [] },
  { code: "F11.951", diagnosis: "Opioid use, unspecified with opioid-induced psychotic disorder with hallucinations", category: "Mental health / substance", search: [] },
  { code: "F11.959", diagnosis: "Opioid use, unspecified with opioid-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F11.981", diagnosis: "Opioid use, unspecified with opioid-induced sexual dysfunction", category: "Mental health / substance", search: [] },
  { code: "F11.982", diagnosis: "Opioid use, unspecified with opioid-induced sleep disorder", category: "Mental health / substance", search: [] },
  { code: "F11.988", diagnosis: "Opioid use, unspecified with other opioid-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F11.99", diagnosis: "Opioid use, unspecified with unspecified opioid-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F11.93", diagnosis: "Opioid use, unspecified with withdrawal", category: "Mental health / substance", search: [] },
  { code: "F11.91", diagnosis: "Opioid use, unspecified, in remission", category: "Mental health / substance", search: [] },
  { code: "F11.90", diagnosis: "Opioid use, unspecified, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F19.129", diagnosis: "Other psychoactive substance abuse with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F19.159", diagnosis: "Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F19.19", diagnosis: "Other psychoactive substance abuse with unspecified psychoactive substance-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F19.139", diagnosis: "Other psychoactive substance abuse with withdrawal, unspecified", category: "Mental health / substance", search: [] },
  { code: "F19.229", diagnosis: "Other psychoactive substance dependence with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F19.259", diagnosis: "Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F19.29", diagnosis: "Other psychoactive substance dependence with unspecified psychoactive substance-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F19.239", diagnosis: "Other psychoactive substance dependence with withdrawal, unspecified", category: "Mental health / substance", search: [] },
  { code: "F19.921", diagnosis: "Other psychoactive substance use, unspecified with intoxication with delirium", category: "Mental health / substance", search: [] },
  { code: "F19.922", diagnosis: "Other psychoactive substance use, unspecified with intoxication with perceptual disturbance", category: "Mental health / substance", search: [] },
  { code: "F19.920", diagnosis: "Other psychoactive substance use, unspecified with intoxication, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F19.929", diagnosis: "Other psychoactive substance use, unspecified with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F19.988", diagnosis: "Other psychoactive substance use, unspecified with other psychoactive substance-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F19.980", diagnosis: "Other psychoactive substance use, unspecified with psychoactive substance-induced anxiety disorder", category: "Mental health / substance", search: [] },
  { code: "F19.94", diagnosis: "Other psychoactive substance use, unspecified with psychoactive substance-induced mood disorder", category: "Mental health / substance", search: [] },
  { code: "F19.96", diagnosis: "Other psychoactive substance use, unspecified with psychoactive substance-induced persisting amnestic disorder", category: "Mental health / substance", search: [] },
  { code: "F19.97", diagnosis: "Other psychoactive substance use, unspecified with psychoactive substance-induced persisting dementia", category: "Mental health / substance", search: [] },
  { code: "F19.950", diagnosis: "Other psychoactive substance use, unspecified with psychoactive substance-induced psychotic disorder with delusions", category: "Mental health / substance", search: [] },
  { code: "F19.951", diagnosis: "Other psychoactive substance use, unspecified with psychoactive substance-induced psychotic disorder with hallucinations", category: "Mental health / substance", search: [] },
  { code: "F19.959", diagnosis: "Other psychoactive substance use, unspecified with psychoactive substance-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F19.981", diagnosis: "Other psychoactive substance use, unspecified with psychoactive substance-induced sexual dysfunction", category: "Mental health / substance", search: [] },
  { code: "F19.982", diagnosis: "Other psychoactive substance use, unspecified with psychoactive substance-induced sleep disorder", category: "Mental health / substance", search: [] },
  { code: "F19.99", diagnosis: "Other psychoactive substance use, unspecified with unspecified psychoactive substance-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F19.931", diagnosis: "Other psychoactive substance use, unspecified with withdrawal delirium", category: "Mental health / substance", search: [] },
  { code: "F19.932", diagnosis: "Other psychoactive substance use, unspecified with withdrawal with perceptual disturbance", category: "Mental health / substance", search: [] },
  { code: "F19.930", diagnosis: "Other psychoactive substance use, unspecified with withdrawal, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F19.939", diagnosis: "Other psychoactive substance use, unspecified with withdrawal, unspecified", category: "Mental health / substance", search: [] },
  { code: "F19.91", diagnosis: "Other psychoactive substance use, unspecified, in remission", category: "Mental health / substance", search: [] },
  { code: "F19.90", diagnosis: "Other psychoactive substance use, unspecified, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F15.129", diagnosis: "Other stimulant abuse with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F15.159", diagnosis: "Other stimulant abuse with stimulant-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F15.19", diagnosis: "Other stimulant abuse with unspecified stimulant-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F15.229", diagnosis: "Other stimulant dependence with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F15.259", diagnosis: "Other stimulant dependence with stimulant-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F15.29", diagnosis: "Other stimulant dependence with unspecified stimulant-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F15.921", diagnosis: "Other stimulant use, unspecified with intoxication delirium", category: "Mental health / substance", search: [] },
  { code: "F15.922", diagnosis: "Other stimulant use, unspecified with intoxication with perceptual disturbance", category: "Mental health / substance", search: [] },
  { code: "F15.920", diagnosis: "Other stimulant use, unspecified with intoxication, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F15.929", diagnosis: "Other stimulant use, unspecified with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F15.988", diagnosis: "Other stimulant use, unspecified with other stimulant-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F15.980", diagnosis: "Other stimulant use, unspecified with stimulant-induced anxiety disorder", category: "Mental health / substance", search: [] },
  { code: "F15.94", diagnosis: "Other stimulant use, unspecified with stimulant-induced mood disorder", category: "Mental health / substance", search: [] },
  { code: "F15.950", diagnosis: "Other stimulant use, unspecified with stimulant-induced psychotic disorder with delusions", category: "Mental health / substance", search: [] },
  { code: "F15.951", diagnosis: "Other stimulant use, unspecified with stimulant-induced psychotic disorder with hallucinations", category: "Mental health / substance", search: [] },
  { code: "F15.959", diagnosis: "Other stimulant use, unspecified with stimulant-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F15.981", diagnosis: "Other stimulant use, unspecified with stimulant-induced sexual dysfunction", category: "Mental health / substance", search: [] },
  { code: "F15.982", diagnosis: "Other stimulant use, unspecified with stimulant-induced sleep disorder", category: "Mental health / substance", search: [] },
  { code: "F15.99", diagnosis: "Other stimulant use, unspecified with unspecified stimulant-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F15.93", diagnosis: "Other stimulant use, unspecified with withdrawal", category: "Mental health / substance", search: [] },
  { code: "F15.91", diagnosis: "Other stimulant use, unspecified, in remission", category: "Mental health / substance", search: [] },
  { code: "F15.90", diagnosis: "Other stimulant use, unspecified, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F34.9", diagnosis: "Persistent mood [affective] disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F40.9", diagnosis: "Phobic anxiety disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F43.11", diagnosis: "Post-traumatic stress disorder, acute", category: "Mental health / substance", search: [] },
  { code: "F43.10", diagnosis: "Post-traumatic stress disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F43.9", diagnosis: "Reaction to severe stress, unspecified", category: "Mental health / substance", search: [] },
  { code: "F13.129", diagnosis: "Sedative, hypnotic or anxiolytic abuse with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F13.159", diagnosis: "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F13.19", diagnosis: "Sedative, hypnotic or anxiolytic abuse with unspecified sedative, hypnotic or anxiolytic-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F13.139", diagnosis: "Sedative, hypnotic or anxiolytic abuse with withdrawal, unspecified", category: "Mental health / substance", search: [] },
  { code: "F13.229", diagnosis: "Sedative, hypnotic or anxiolytic dependence with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F13.259", diagnosis: "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F13.29", diagnosis: "Sedative, hypnotic or anxiolytic dependence with unspecified sedative, hypnotic or anxiolytic-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F13.239", diagnosis: "Sedative, hypnotic or anxiolytic dependence with withdrawal, unspecified", category: "Mental health / substance", search: [] },
  { code: "F13.921", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with intoxication delirium", category: "Mental health / substance", search: [] },
  { code: "F13.920", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with intoxication, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F13.929", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with intoxication, unspecified", category: "Mental health / substance", search: [] },
  { code: "F13.988", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with other sedative, hypnotic or anxiolytic-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F13.980", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced anxiety disorder", category: "Mental health / substance", search: [] },
  { code: "F13.94", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced mood disorder", category: "Mental health / substance", search: [] },
  { code: "F13.96", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced persisting amnestic disorder", category: "Mental health / substance", search: [] },
  { code: "F13.97", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced persisting dementia", category: "Mental health / substance", search: [] },
  { code: "F13.950", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder with delusions", category: "Mental health / substance", search: [] },
  { code: "F13.951", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder with hallucinations", category: "Mental health / substance", search: [] },
  { code: "F13.959", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F13.981", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced sexual dysfunction", category: "Mental health / substance", search: [] },
  { code: "F13.982", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced sleep disorder", category: "Mental health / substance", search: [] },
  { code: "F13.99", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with unspecified sedative, hypnotic or anxiolytic-induced disorder", category: "Mental health / substance", search: [] },
  { code: "F13.931", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with withdrawal delirium", category: "Mental health / substance", search: [] },
  { code: "F13.932", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with withdrawal with perceptual disturbances", category: "Mental health / substance", search: [] },
  { code: "F13.930", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with withdrawal, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F13.939", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified with withdrawal, unspecified", category: "Mental health / substance", search: [] },
  { code: "F13.91", diagnosis: "Sedative, hypnotic or anxiolytic use, unspecified, in remission", category: "Mental health / substance", search: [] },
  { code: "F13.90", diagnosis: "Sedative, hypnotic, or anxiolytic use, unspecified, uncomplicated", category: "Mental health / substance", search: [] },
  { code: "F40.10", diagnosis: "Social phobia, unspecified", category: "Mental health / substance", search: [] },
  { code: "F45.9", diagnosis: "Somatoform disorder, unspecified", category: "Mental health / substance", search: [] },
  { code: "F39", diagnosis: "Unspecified mood [affective] disorder", category: "Mental health / substance", search: [] },
  { code: "M21.539", diagnosis: "Acquired clawfoot, unspecified foot", category: "Musculoskeletal", search: [] },
  { code: "M21.519", diagnosis: "Acquired clawhand, unspecified hand", category: "Musculoskeletal", search: [] },
  { code: "M21.549", diagnosis: "Acquired clubfoot, unspecified foot", category: "Musculoskeletal", search: [] },
  { code: "M21.529", diagnosis: "Acquired clubhand, unspecified hand", category: "Musculoskeletal", search: [] },
  { code: "M20.62", diagnosis: "Acquired deformities of toe(s), unspecified, left foot", category: "Musculoskeletal", search: [] },
  { code: "M20.61", diagnosis: "Acquired deformities of toe(s), unspecified, right foot", category: "Musculoskeletal", search: [] },
  { code: "M20.60", diagnosis: "Acquired deformities of toe(s), unspecified, unspecified foot", category: "Musculoskeletal", search: [] },
  { code: "M26.619", diagnosis: "Adhesions and ankylosis of temporomandibular joint, unspecified side", category: "Musculoskeletal", search: [] },
  { code: "M24.673", diagnosis: "Ankylosis, unspecified ankle", category: "Musculoskeletal", search: [] },
  { code: "M24.629", diagnosis: "Ankylosis, unspecified elbow", category: "Musculoskeletal", search: [] },
  { code: "M24.676", diagnosis: "Ankylosis, unspecified foot", category: "Musculoskeletal", search: [] },
  { code: "M24.649", diagnosis: "Ankylosis, unspecified hand", category: "Musculoskeletal", search: [] },
  { code: "M24.659", diagnosis: "Ankylosis, unspecified hip", category: "Musculoskeletal", search: [] },
  { code: "M24.60", diagnosis: "Ankylosis, unspecified joint", category: "Musculoskeletal", search: [] },
  { code: "M24.669", diagnosis: "Ankylosis, unspecified knee", category: "Musculoskeletal", search: [] },
  { code: "M24.619", diagnosis: "Ankylosis, unspecified shoulder", category: "Musculoskeletal", search: [] },
  { code: "M24.639", diagnosis: "Ankylosis, unspecified wrist", category: "Musculoskeletal", search: [] },
];

export const OFFICIAL_ICD10_CONDITION_SELECT_OPTIONS = OFFICIAL_ICD10_CONDITION_OPTIONS.map((item) => ({
  value: item.code,
  label: `${item.code} - ${item.diagnosis}`,
}));

export function officialIcd10ConditionMetaFor(code: string): Icd10ConditionOption | null {
  return OFFICIAL_ICD10_CONDITION_OPTIONS.find((item) => item.code === code) ?? null;
}
